import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { ReportEntity } from './entities/report.entity';
import { CreateReportDto } from './dto/create-report.dto';

@Injectable()
export class ReportsService {
  constructor(
    @InjectRepository(ReportEntity)
    private readonly reportRepository: Repository<ReportEntity>,
  ) {}

  async onModuleInit() {
    const count = await this.reportRepository.count();

    if (count === 0) {
      await this.reportRepository.save([
        {
          title: 'Weekly Productivity Report',
          type: 'Productivity',
          date: 'Aug 18, 2026',
          status: 'Ready',
          agent: 'Analytics Agent',
          description:
            'Workspace productivity overview including tasks, activity and performance.',
        },
        {
          title: 'Project Performance Report',
          type: 'Project',
          date: 'Aug 17, 2026',
          status: 'Ready',
          agent: 'Manager Agent',
          description:
            'Project progress, completion status and overall project performance.',
        },
        {
          title: 'AI Agent Activity Report',
          type: 'AI Analytics',
          date: 'Aug 16, 2026',
          status: 'Ready',
          agent: 'Analytics Agent',
          description:
            'AI agent activity, assigned work and agent performance overview.',
        },
        {
          title: 'Team Performance Report',
          type: 'Team',
          date: 'Aug 15, 2026',
          status: 'Processing',
          agent: 'Manager Agent',
          description:
            'Team performance, productivity and collaboration overview.',
        },
      ]);
    }
  }

  async getReports() {
    return this.reportRepository.find({
      order: {
        id: 'DESC',
      },
    });
  }

  async getReportById(id: number) {
    return this.reportRepository.findOne({
      where: { id },
    });
  }

  async createReport(dto: CreateReportDto) {
    const today = new Date();

    const formattedDate = today.toLocaleDateString('en-US', {
      month: 'short',
      day: '2-digit',
      year: 'numeric',
    });

    const report = this.reportRepository.create({
      title: dto.title,
      type: dto.type,
      date: formattedDate,
      status: 'Processing',
      agent: dto.agent,
      description:
        dto.description ??
        `${dto.type} report generated by ${dto.agent}.`,
    });

    const savedReport = await this.reportRepository.save(report);

    return {
      success: true,
      message: 'Report created successfully.',
      report: savedReport,
    };
  }

  async completeReport(id: number) {
    const report = await this.getReportById(id);

    if (!report) {
      return {
        success: false,
        message: 'Report not found.',
      };
    }

    report.status = 'Ready';

    const updatedReport = await this.reportRepository.save(report);

    return {
      success: true,
      message: 'Report is ready.',
      report: updatedReport,
    };
  }

  async deleteReport(id: number) {
    const report = await this.getReportById(id);

    if (!report) {
      return {
        success: false,
        message: 'Report not found.',
      };
    }

    await this.reportRepository.delete(id);

    return {
      success: true,
      message: 'Report deleted successfully.',
    };
  }
}